# Force Railway to build Python backend only (ignore Flutter)
providers = ["python"]

[phases.setup]
nixPkgs = ["python311", "gcc", "libffi"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
# No build phase needed for Flask

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 300 --worker-class sync railway_app:app"
